spring:
  application:
    名字: adg-rule
  profiles:
    已激活: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  rule:
    #远程规则
    remote:
      - 'https://raw.githubusercontent.com/lingeringsound/10007_auto/master/all'#>10007_auto
      - 'https://github.com/Potterli20/file/releases/download/github-hosts/Accelerate-Hosts.txt'#>yhosts
      - 'https://github.com/Potterli20/file/releases/download/github-hosts/gfw-hosts.txt'#>yhosts
      - 'https://github.com/Potterli20/file/releases/download/github-hosts/bilibili-hosts.txt'#>yhosts
      - 'https://adrules.top/dns.txt'#>yhosts
      - 'https://adrules.top/hosts.txt'#>yhosts
      - 'https://anti-ad.net/easylist.txt' #name: anti-AD (仅合并去重，使用该规则不代表支持其观点)
      #自用添加↓
      - 'https://raw.githubusercontent.com/8680/GOODBYEADS/master/rules.txt' #name: GOODBYEADS
      - 'https://raw.hellogithub.com/hosts' #name: github520
      #KoolProxy规则
      #- 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/koolproxy.txt' #name:静态白名单规则
      - 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/daily.txt' #name:每日规则
      #- 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/adg.txt' #name:AdGuard规则
      #- 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/adgk.txt' #name:Banben规则
      #- 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/yhosts.txt' #name:Yhosts规则
      - 'https://raw.iqiq.io/ilxp/koolproxy/master/rules/steven.txt' #name:StevenBlack规则
      #uBlock内置规则
      - 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/filters.txt' #name: uBlock filters
      - 'https://ublockorigin.pages.dev/filters/badware.txt' #name: uBlock filters – Badware risks
      - 'https://gitcdn.link/cdn/uBlockOrigin/uAssetsCDN/main/filters/privacy.txt' #name: uBlock filters – Privacy
      - 'https://ublockorigin.github.io/uAssets/filters/quick-fixes.txt' #name: uBlock filters – Quick fixes
      - 'https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/resource-abuse.txt' #name: uBlock filters – Resource abuse
      - 'https://gitcdn.link/cdn/uBlockOrigin/uAssetsCDN/main/filters/unbreak.txt' #name: uBlock filters – Unbreak
      - 'https://filters.adtidy.org/extension/ublock/filters/11.txt' #name: AdGuard Mobile Ads移动设备
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - 'mylist.txt'
  output:
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:    #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      adgh.txt:
        - DOMAIN
        - REGEX
#        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
